// Diagram -> Mermaid `architecture-beta`.
import { buildModel, centreOf, makeIdentifiers, resolveEdges, walkTree, type ExportInput, type ModelNode } from './model'

export type MermaidIconSet = 'builtin' | 'aws'

export type MermaidOptions = {
  /**
   * `builtin` uses Mermaid's own icons (cloud, database, disk, internet, server) and renders
   * anywhere, including GitHub. `aws` uses the iconify "logos" pack, which the host page
   * must register.
   */
  iconSet?: MermaidIconSet
}

const INDENT = '    '
const RESERVED = new Set(['architecture', 'group', 'service', 'junction', 'in', 'title', 'acctitle', 'accdescr'])

/** Titles can't contain square brackets, and `%%` would start a comment. */
const title = (text: string) => text.replace(/\[/g, '(').replace(/\]/g, ')').replace(/%%/g, '%').trim()

function builtinIcon(node: ModelNode) {
  const folder = node.iconId?.match(/^(?:svc|res):([^/]+)\//)?.[1]
  if (folder === 'Databases') return 'database'
  if (folder === 'Storage') return 'disk'
  if (folder === 'Networking-Content-Delivery') return 'internet'
  return 'server'
}

function serviceIcon(node: ModelNode, iconSet: MermaidIconSet) {
  const icon = node.mapping?.mermaidIcon
  if (icon && (iconSet === 'aws' || !icon.includes(':'))) return icon
  return builtinIcon(node)
}

function groupIcon(node: ModelNode, iconSet: MermaidIconSet) {
  if (iconSet === 'aws' && node.groupType === 'vpc') return 'logos:aws-vpc'
  if (iconSet === 'aws' && node.groupType === 'aws-cloud') return 'logos:aws'
  return 'cloud'
}

/** Offsets smaller than this share of the main direction count as straight, not diagonal. */
const DIAGONAL_RATIO = 0.4

/**
 * Sides the edge leaves and enters by. Mermaid positions services from these, so they follow
 * the drawn layout: straight pairs (R→L) for nodes in line, corner pairs (B→L) for diagonal
 * ones. Without corners, several targets on one side collapse into a single row.
 */
function sides(a: ModelNode, b: ModelNode): [string, string] {
  const [ca, cb] = [centreOf(a), centreOf(b)]
  const dx = cb.x - ca.x
  const dy = cb.y - ca.y
  const horizontal = dx >= 0 ? (['R', 'L'] as const) : (['L', 'R'] as const)
  const vertical = dy >= 0 ? (['B', 'T'] as const) : (['T', 'B'] as const)
  if (Math.abs(dx) >= Math.abs(dy)) {
    return Math.abs(dy) > DIAGONAL_RATIO * Math.abs(dx) ? [vertical[0], horizontal[1]] : [...horizontal]
  }
  return Math.abs(dx) > DIAGONAL_RATIO * Math.abs(dy) ? [horizontal[0], vertical[1]] : [...vertical]
}

function arrow(arrows: 'end' | 'both' | 'none', label: string) {
  const middle = label ? `-[${label}]-` : '--'
  if (arrows === 'none') return middle
  return arrows === 'both' ? `<${middle}>` : `${middle}>`
}

export function exportMermaid(input: ExportInput, options: MermaidOptions = {}): string {
  const iconSet = options.iconSet ?? 'builtin'
  const model = buildModel(input)
  const ids = makeIdentifiers(model, RESERVED)
  const lines = ['architecture-beta', `${INDENT}%% ${title(model.name)} (generated by AWS Diagram Studio)`]

  walkTree(model, {
    enter: (node) => {
      const id = ids.get(node.id)!
      const parent = node.parentId ? ` in ${ids.get(node.parentId)}` : ''
      if (node.kind === 'group') {
        lines.push(`${INDENT}group ${id}(${groupIcon(node, iconSet)})[${title(node.label)}]${parent}`)
        return
      }
      if (!node.mapping || (iconSet === 'aws' && !node.mapping.mermaidIcon)) {
        lines.push(`${INDENT}%% TODO: unmapped ${title(node.serviceName)}`)
      }
      lines.push(`${INDENT}service ${id}(${serviceIcon(node, iconSet)})[${title(node.label)}]${parent}`)
    },
  })

  if (model.nodes.size === 0) lines.push(`${INDENT}%% The diagram is empty`)
  for (const note of model.notes) {
    lines.push(`${INDENT}%% Note${note.parentLabel ? ` (in ${title(note.parentLabel)})` : ''}: ${title(note.label)}`)
  }

  const { resolved, skipped } = resolveEdges(model)
  for (const { edge, source, target } of resolved) {
    const [sourceSide, targetSide] = sides(source.node, target.node)
    // {group} attaches the edge to the group border when it was drawn to the group itself.
    const sourceGroup = source.viaGroup && source.node.parentId === source.viaGroup.id ? '{group}' : ''
    const targetGroup = target.viaGroup && target.node.parentId === target.viaGroup.id ? '{group}' : ''
    lines.push(
      `${INDENT}${ids.get(source.node.id)}${sourceGroup}:${sourceSide} ${arrow(edge.arrows, title(edge.label))} ` +
        `${targetSide}:${ids.get(target.node.id)}${targetGroup}`,
    )
  }
  for (const { edge, reason } of skipped) {
    lines.push(`${INDENT}%% Skipped connection${edge.label ? ` "${title(edge.label)}"` : ''}: ${reason}`)
  }

  return `${lines.join('\n')}\n`
}
