// Diagram -> runnable Python script for mingrammer's `diagrams` library.
import { groupStyle } from '../data/groups'
import {
  buildModel,
  makeIdentifiers,
  resolveEdges,
  toSnakeCase,
  walkTree,
  type ExportInput,
  type ModelEdge,
  type ModelNode,
} from './model'

const INDENT = '    '
const FALLBACK_CLASS = 'diagrams.aws.general.General'
const CLASS_PATH = /^diagrams\.aws\.[a-z0-9_]+\.[A-Za-z0-9_]+$/

// Python keywords, plus the names this script imports from `diagrams`.
const RESERVED = new Set([
  'false', 'none', 'true', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del',
  'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal',
  'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield', 'match', 'case', 'type',
  'cluster', 'diagram', 'edge', 'diagrams',
])

/** JSON string literals are valid Python string literals. */
const str = (text: string) => JSON.stringify(text)

const classPath = (node: ModelNode) => {
  const path = node.mapping?.diagramsClass
  return path && CLASS_PATH.test(path) ? path : FALLBACK_CLASS
}

const pascal = (text: string) => text.replace(/(^|_)([a-z])/g, (_, __, c: string) => c.toUpperCase())

/** `from … import …` lines, aliasing classes whose names clash across modules. */
function importsFor(icons: ModelNode[]) {
  const paths = [...new Set(icons.map(classPath))].sort()
  const localNames = new Map<string, string>()
  const taken = new Set<string>(['Cluster', 'Diagram', 'Edge'])
  for (const path of paths) {
    const parts = path.split('.')
    const cls = parts.at(-1)!
    let local = cls
    if (taken.has(local)) local = `${pascal(parts.at(-2)!)}${cls}`
    taken.add(local)
    localNames.set(path, local)
  }

  const byModule = new Map<string, string[]>()
  for (const [path, local] of localNames) {
    const cls = path.split('.').at(-1)!
    const module = path.slice(0, -cls.length - 1)
    byModule.set(module, [...(byModule.get(module) ?? []), local === cls ? cls : `${cls} as ${local}`])
  }
  const lines = [...byModule]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([module, names]) => `from ${module} import ${names.sort().join(', ')}`)
  return { lines, localNames }
}

function clusterAttributes(node: ModelNode) {
  const style = groupStyle(node.groupType ?? 'generic')
  const attributes: Record<string, string> = {
    bgcolor: style.fill ?? 'transparent',
    pencolor: style.stroke,
    fontcolor: style.text,
    ...(style.dashed && { style: 'rounded,dashed' }),
  }
  return `{${Object.entries(attributes).map(([key, value]) => `${str(key)}: ${str(value)}`).join(', ')}}`
}

function connection(source: string, target: string, edge: ModelEdge) {
  const attributes = [edge.label && `label=${str(edge.label)}`, edge.dashed && 'style="dashed"'].filter(Boolean)
  if (edge.arrows === 'both') {
    return `${source} - Edge(${[...attributes, 'forward=True', 'reverse=True'].join(', ')}) - ${target}`
  }
  const operator = edge.arrows === 'none' ? '-' : '>>'
  return attributes.length
    ? `${source} ${operator} Edge(${attributes.join(', ')}) ${operator} ${target}`
    : `${source} ${operator} ${target}`
}

export function exportPython(input: ExportInput): string {
  const model = buildModel(input)
  const ids = makeIdentifiers(model, RESERVED)
  const icons = [...model.nodes.values()].filter((node) => node.kind === 'icon')
  const { lines: imports, localNames } = importsFor(icons)
  const fileName = toSnakeCase(model.name) || 'diagram'

  const lines = [
    `# ${model.name}: generated by AWS Diagram Studio`,
    '# Requires Graphviz (https://graphviz.org/download/) and the diagrams package: pip install diagrams',
    `# Run: python ${fileName}.py  (writes ${fileName}.png)`,
    '',
    'from diagrams import Cluster, Diagram, Edge',
    ...imports,
    '',
    `with Diagram(${str(model.name)}, filename=${str(fileName)}, show=False, direction="LR"):`,
  ]

  walkTree(model, {
    enter: (node, depth) => {
      const pad = INDENT.repeat(depth + 1)
      if (node.kind === 'group') {
        lines.push(`${pad}with Cluster(${str(node.label)}, graph_attr=${clusterAttributes(node)}):`)
        if (!model.childrenOf.get(node.id)?.length) lines.push(`${pad}${INDENT}pass`)
        return
      }
      if (!node.mapping?.diagramsClass) lines.push(`${pad}# TODO: unmapped ${node.serviceName}`)
      lines.push(`${pad}${ids.get(node.id)} = ${localNames.get(classPath(node))}(${str(node.label)})`)
    },
  })
  if (model.nodes.size === 0) lines.push(`${INDENT}pass  # The diagram is empty`)

  const { resolved, skipped } = resolveEdges(model)
  if (resolved.length || skipped.length) lines.push('')
  for (const { edge, source, target } of resolved) {
    const group = source.viaGroup ?? target.viaGroup
    if (group) lines.push(`${INDENT}# Connected to the "${group.label}" group, drawn to its first service`)
    lines.push(`${INDENT}${connection(ids.get(source.node.id)!, ids.get(target.node.id)!, edge)}`)
  }
  for (const { edge, reason } of skipped) {
    lines.push(`${INDENT}# Skipped connection${edge.label ? ` "${edge.label}"` : ''}: ${reason}`)
  }

  return `${lines.join('\n')}\n`
}
